### PR TITLE
vm/mman: handle properly munmap of chunks larger than SIZE_PAGE

### PR DESCRIPTION
**Pull request by badochov**
JIRA: RTOS-893

## Description
Munmap handled badly segments bigger that SIZE_PAGE, after it the rb tree was in corrupted state.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: ia-32

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/581
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by badochov** [comment]
> Perhaps we could use `vm_mapEntrySplit` in case of the "in the middle" `munmap`

Only thing that comes to my mind is changing this part to

```c
			s = map_alloc();
			/* This case if only possible if an unmapped region is in the middle of a single entry,
			 * so there is no possibility of partially unmapping. */
			if (s == NULL) {
				return -ENOMEM;
			}
			vm_mapEntrySplit(proc, map, e, s, overlapStart);
			continue; /* Process in next iteration. */
```

What do you think about it?

**Comment by agkaminski** [comment]
> > Perhaps we could use `vm_mapEntrySplit` in case of the "in the middle" `munmap`
> 
> Only thing that comes to my mind is changing this part to
> 
> ```c
> 			s = map_alloc();
> 			/* This case if only possible if an unmapped region is in the middle of a single entry,
> 			 * so there is no possibility of partially unmapping. */
> 			if (s == NULL) {
> 				return -ENOMEM;
> 			}
> 			vm_mapEntrySplit(proc, map, e, s, overlapStart);
> 			continue; /* Process in next iteration. */
> ```
> 
> What do you think about it?

Looks nice!

**Review by agkaminski — APPROVED** [review]
LGTM

**Comment by badochov** [comment]
@agkaminski @damianloew
`unix-socket` test failed on CI on armv7a-qemu due to timeout 358ms instead of 350ms, should I be concerned?

https://github.com/phoenix-rtos/phoenix-rtos-kernel/actions/runs/11050286361/job/30697841405?pr=578

**Comment by agkaminski** [comment]
> @agkaminski @damianloew `unix-socket` test failed on CI on armv7a-qemu due to timeout 358ms instead of 350ms, should I be concerned? Munmap changes should change this test, as in poll and gettime theres no munmap
> 
> https://github.com/phoenix-rtos/phoenix-rtos-kernel/actions/runs/11050286361/job/30697841405?pr=578

I guess it did pass on the rerun. @damianloew perhaps this timeout is somewhat on the edge?

**Comment by damianloew** [comment]
> > @agkaminski @damianloew `unix-socket` test failed on CI on armv7a-qemu due to timeout 358ms instead of 350ms, should I be concerned? Munmap changes should change this test, as in poll and gettime theres no munmap
> > https://github.com/phoenix-rtos/phoenix-rtos-kernel/actions/runs/11050286361/job/30697841405?pr=578
> 
> I guess it did pass on the rerun. @damianloew perhaps this timeout is somewhat on the edge?

Yeah, we had a similar problem some time ago and changed the value to 350 from 310:
https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/350

We will consider increasing the value more - probably we will check 400. However I am not sure whether higher values are caused by our system or by the gh machine on which the tests are executed

**Pull request merged**
