### PR TITLE
schedule: Allow stack canary enable independent of NDEBUG

### PR DESCRIPTION
**Pull request by agkaminski**
DONE: RTOS-310

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
  - https://github.com/phoenix-rtos/phoenix-rtos-kernel/pull/360
- [x] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by nalajcie** [comment]
not sure how should I enable the feature in a kosher way. I can't override CLFAGS from command-line, so I need to dig into Makefiles to do so..., if so - please at least add in kernel Makefile:
```make
# uncomment to enable stack canary checking
# CFLAGS += -DSTACK_CANARY
```

IMHO, it would be better to do it automatically based on some ENV variable, so no need to manually edit makes, eg:
```make
## compilation options (specify them in project file / env)
ifneq ($(KERNEL_STACK_CANARY),)
  CFLAGS += -DSTACK_CANARY
endif
```

I would appreciate specific documentation page about debugging tips for our OS (not right away, but IMHO much needed :)).

**Comment by agkaminski** [comment]
@nalajcie imho best way would be to add setting -DSTACK_CANARY to phoenix-rtos-build based on ENV

**Comment by nalajcie** [comment]
> @nalajcie imho best way would be to add setting -DSTACK_CANARY to phoenix-rtos-build based on ENV

The practice is to:
 - do so on "module level" not to pollute build environment of other unrelated components
 - use unique prefixes for all possible DEFINE's (probably module prefixes) to avoid name clashing
 - generating global `config.h` (nice, because incremental build works on env changes then)

Our preference would probably be the first for now.

**Comment by agkaminski** [comment]
Ok

**Review by nalajcie — APPROVED** [review]
would prefer enabling by env but still better than nothing :)

**Comment by agkaminski** [comment]
You said you prefer option 1 xP

**Comment by nalajcie** [comment]
image

Precision of language :P.

Not a problem, I would change it when it would start to bother me too much ;).

**Pull request merged**
