### PR TITLE
ia32: hal_cpuFeatures() fixed the 'nx' feature check

### PR DESCRIPTION
**Pull request by kemonats**
## Description

Now the '`nx'` feature is not shown for a processor that has it.
The variable `eax` of the `cpu_feature_t` structure is of type `u32`, and is never less  than `0`.
Changes:
1. Change variable `eax` to type `int`.
If the `eax` variable is to remain of type `u32`, then you need to cast the variable `eax` to `int` type .
2. Removed the `overflow` variable. If the buffer size is too small then exit the `for` loop.
3. The `'+'` char is added to the second and subsequent features.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).
ia32-generic

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Comment by agkaminski** [comment]
Sorry for taking interest this late, could you please rebase this PR so we can merge it?

**Review by gerard5 — COMMENTED** [review]
I verified the correctness of operation on an AMD cpu on which the `nx` bit is set. 
@kemonats, please rebase the commits. I'll appreciate your pull-request be merged.

2023-03-25-221144_1013x111_scrot

Verified - ok, when `features` string overflows (manually resized [buffer)](https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/1b41faf6f92bfa2a28d0fa3e04db5547348041ee/main.c#L96):
2023-03-25-223908_557x90_scrot

**Comment by kemonats** [comment]
Done.
Should I delete the comment on line 542?

**Comment by gerard5** [comment]
> Done. Should I delete the comment on line 542 ?

Yes, please.

**Review by gerard5 — COMMENTED** [review]
Apart from casting to `int` instead of `s32` (see comment), the rest looks good to me. I see that this change removes the redundant (last) `+` in case the features list string does not fit in the buffer, this looks good to me.

**Review by gerard5 — APPROVED** [review]
Looks good to me.

**Review by agkaminski — APPROVED** [review]

**Pull request merged**
