### PR TITLE
hal/ia32: moved PCI driver to separate module + extended implementati…

### PR DESCRIPTION
**Pull request by Maxez**
…on for PCI capability list (based on posixrev branch)
Changes proposed in this PR are necessary for VirtIO PCI devices detection and initialization in libvirtio.

### CODE REVIEW

**Comment by pawelpisarczyk** [comment]
I don't understand why you move the most important `cpu` structure from cpu.c into pci?

**Comment by Maxez** [comment]
> 
> 
> I don't understand why you move the most important `cpu` structure from cpu.c into pci?

I didn't move the cpu structure - it's just an export declaration. We need this for cpu.lock access when using spinlocks.

**Comment by pawelpisarczyk** [comment]
It is very bad idea to use the same structure in pci.c (separate module). If you need the spinlock to synchronize access to correctly enumerate PCI bus please define `pci_common` structure holding spinlock in pci.c, initialize spinlock during HAL startup and use this separate spinlock in pci.c functions.

**Comment by Maxez** [comment]
I moved cpu.lock to pci_common.lock as suggested (cpu.lock was used for PCI access synchronization only).

**Comment by pawelpisarczyk** [comment]
Could you rename `lock` to `spinlock` and change this horrible line `dv |= !!enable << 2;` in setBusmaster function?

**Comment by Maxez** [comment]
> Could you rename `lock` to `spinlock` and change this horrible line `dv |= !!enable << 2;` in `hal_pciSetBusmaster` function?

Done. I hope `hal_pciSetBusmaster()` is more readable now.

**Comment by pawelpisarczyk** [comment]
I meant to change this `dv |= !!enable << 2;` into `dv |= (enable << 2)`. I didn't understand this double negation.

**Comment by Maxez** [comment]
> I meant to change this `dv |= !!enable << 2;` into `dv |= (enable << 2)`. I didn't understand this double negation.

The double negation casts u8 value to boolean (0 or 1). I think it is fine - a bit of defensive programming. Anyway I removed the double negation.

**Pull request merged**
