### PR TITLE
toolchain: bump version to gcc-9.3.0, binutils-2.34, add target riscv64-phoenix-elf

### PR DESCRIPTION
**Pull request by nalajcie**
Other enhancements:
 - binutils: enable LTO support
 - GCC: use download_prerequisites script
- GCC: use provided common multilib configuration instead of phoenix
custom one
 - provide per-version patches
 - make it possible to build different targets from the same sources
 - log script progress

Please build new toolchains by issuing commands like (not simultaneously):
```bash
./build-toolchain.sh arm-phoenix ~/toolchain-phrtos3/
./build-toolchain.sh i386-pc-phoenix ~/toolchain-phrtos3/
./build-toolchain.sh riscv64-phoenix-elf ~/toolchain-phrtos3/
```

and test if all current sources compile with it.

Please note that the gcc-9.3.0 have additional checks (over gcc-7.1.0) against common programming errors, so current code may not compile until fixed.

### CODE REVIEW

**Comment by anglov** [comment]
stm32l1 projects seems to work (not fully tested – just build and flashed)

**Comment by agkaminski** [comment]
I'll fix new warnings asap.

**Comment by agkaminski** [comment]
stm32l4 project works as well.

**Comment by pawelpisarczyk** [comment]
Works fine. I have tested compilation of phoenix-rtos-kernel and libphoenix.

**Comment by pawelpisarczyk** [comment]
Alek, please accept pull request

**Comment by agkaminski** [comment]
Paweł, have you tested ia32 toolchain? I've asked Łukasz to test it for us.

**Comment by pawelpisarczyk** [comment]
Yes. I've tested all toolchains - ia32, arm and riscv64

**Pull request merged**
