### PR TITLE
hal/cortex-m: Unify SCB and NVIC into SCS

### PR DESCRIPTION
**Pull request by agkaminski**
JIRA: RTOS-886

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (refactoring, style fixes, git/CI config, submodule management, no code logic changes)

## How Has This Been Tested?

- [x] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

### CODE REVIEW

**Review by Darchiv — APPROVED** [review]
LGTM. Adding @anglov

**Review by anglov — DISMISSED** [review]
Not checked manually, but looks good

I would suggest to clean up hal_* functions name to match module name in future

**Comment by Darchiv** [comment]
> > Not checked manually, but looks good
> > I would suggest to clean up hal_* functions name to match module name in future
> 
> Thought about it and I'm not sure about that. nvic/scb function names seem somewhat nice, although it violates our naming convention (prefix is not a module name). @Darchiv I can change that in the scope of this PR, should I?

Not sure. How will you rename them? `_hal_scsNvicSetIRQ()` is somewhat long, but `_hal_scsSetIRQ()` does not relate to the module it operates in.

**Comment by agkaminski** [comment]
> > > Not checked manually, but looks good
> > > I would suggest to clean up hal_* functions name to match module name in future
> > 
> > 
> > Thought about it and I'm not sure about that. nvic/scb function names seem somewhat nice, although it violates our naming convention (prefix is not a module name). @Darchiv I can change that in the scope of this PR, should I?
> 
> Not sure. How will you rename them? `_hal_scsNvicSetIRQ()` is somewhat long, but `_hal_scsSetIRQ()` does not relate to the module it operates in.

That's my problem exactly :smile: Pure SCS seems fine to me, though

**Comment by Darchiv** [comment]
> > > > Not checked manually, but looks good
> > > > I would suggest to clean up hal_* functions name to match module name in future
> > > 
> > > 
> > > Thought about it and I'm not sure about that. nvic/scb function names seem somewhat nice, although it violates our naming convention (prefix is not a module name). @Darchiv I can change that in the scope of this PR, should I?
> > 
> > 
> > Not sure. How will you rename them? `_hal_scsNvicSetIRQ()` is somewhat long, but `_hal_scsSetIRQ()` does not relate to the module it operates in.
> 
> That's my problem exactly 😄 Pure SCS seems fine to me, though

SCS is fine, but I think functions should have consistent names, e.g.
```
void _hal_nvicSetIRQ(s8 irqn, u8 state);
void _hal_nvicSetPriority(s8 irqn, u32 priority);
void _hal_nvicSetPending(s8 irqn);
int _hal_nvicGetPendingIRQ(s8 irqn);
int _hal_nvicGetActive(s8 irqn);
```
Sometimes with `IRQ`, sometimes not. Maybe even move the common part to be a prefix? E.g.
```
void _hal_scsIRQSet(s8 irqn, u8 state);
void _hal_scsIRQSetPriority(s8 irqn, u32 priority);
void _hal_scsIRQSetPending(s8 irqn);
int _hal_scsIRQGetPending(s8 irqn);
int _hal_scsIRQGetActive(s8 irqn);
```
but this doesn't look as easy to read as I thought it would.

**Comment by agkaminski** [comment]
> > > > > Not checked manually, but looks good
> > > > > I would suggest to clean up hal_* functions name to match module name in future
> > > > 
> > > > 
> > > > Thought about it and I'm not sure about that. nvic/scb function names seem somewhat nice, although it violates our naming convention (prefix is not a module name). @Darchiv I can change that in the scope of this PR, should I?
> > > 
> > > 
> > > Not sure. How will you rename them? `_hal_scsNvicSetIRQ()` is somewhat long, but `_hal_scsSetIRQ()` does not relate to the module it operates in.
> > 
> > 
> > That's my problem exactly 😄 Pure SCS seems fine to me, though
> 
> SCS is fine, but I think functions should have consistent names, e.g.
> 
> ```
> void _hal_nvicSetIRQ(s8 irqn, u8 state);
> void _hal_nvicSetPriority(s8 irqn, u32 priority);
> void _hal_nvicSetPending(s8 irqn);
> int _hal_nvicGetPendingIRQ(s8 irqn);
> int _hal_nvicGetActive(s8 irqn);
> ```
> 
> Sometimes with `IRQ`, sometimes not. Maybe even move the common part to be a prefix? E.g.
> 
> ```
> void _hal_scsIRQSet(s8 irqn, u8 state);
> void _hal_scsIRQSetPriority(s8 irqn, u32 priority);
> void _hal_scsIRQSetPending(s8 irqn);
> int _hal_scsIRQGetPending(s8 irqn);
> int _hal_scsIRQGetActive(s8 irqn);
> ```
> 
> but this doesn't look as easy to read as I thought it would.

I like your proposition, imho it is readable, sticks to our naming convention better and generally better than the current version.

**Review by Darchiv — APPROVED** [review]

**Pull request merged**
